language: node_js
node_js:
- '8.10.0'
branches:
  only:
  - master
before_install:
- export TZ=Asia/Shanghai
- openssl aes-256-cbc -K $encrypted_e011a6d7eebf_key -iv $encrypted_e011a6d7eebf_iv -in .travis/id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- eval $(ssh-agent)
- ssh-add ~/.ssh/id_rsa
- cp .travis/ssh_config ~/.ssh/config
before_script:
- git config --global user.name 'Sabrina Luo'
- git config --global user.email 'luohaojing@gmail.com'
- git clone --depth=1 git@github.com:sabrinaluo/hexo-theme-replica.git themes/replica
##clone gh-pages branch only, into .deploy_git folder, so that commit history can be kept
- git clone git@github.com:sabrinaluo/tech.git -b gh-pages --single-branch .deploy_git
script:
- npm run build
after_success:
- npm run deploy
